site_name: Abel Documentation

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs

nav:
  - Home: index.md
  - Manual:
    - Getting Started:
      - Installation: getting-started/installation.md
      - Hello, World: getting-started/hello-world.md
      - Package: getting-started/package.md
    - Runtime:
      - Security: runtime/security.md
      - Async: runtime/async.md
      - Modifications: runtime/modifications.md
      - File System: runtime/file-system.md
    - Server:
      - Managing Services: server/manage.md
      - Configuration: server/config.md
  - API:
    - Runtime:
      - Builtins: api/runtime/builtins.md
      - Abel API: api/runtime/abel.md
      - HTTP: api/runtime/http.md
      - File System: api/runtime/fs.md
      - JSON: api/runtime/json.md
      - Crypto: api/runtime/crypto.md
      - Testing: api/runtime/testing.md
    - Server:
      - Service: api/server/service.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
