site_name: Abel Documentation

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs

nav:
  - Home: index.md
  - Manual:
    - Getting Started:
      - Installation: getting-started/installation.md
      - Hello, World: getting-started/hello-world.md
      - Package: getting-started/package.md
    - Sandbox:
      - Security: sandbox/security.md
      - Modifications: sandbox/modifications.md
      - File System: sandbox/file-system.md
    - Server:
      - Managing Services: server/manage.md
      - Configuration: server/config.md
  - API:
    - Service: api/service.md
    - Sandbox:
      - Builtins: api/sandbox/builtins.md
      - Abel API: api/sandbox/abel.md
      - HTTP: api/sandbox/http.md
      - File System: api/sandbox/fs.md
      - JSON: api/sandbox/json.md
      - Crypto: api/sandbox/crypto.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
